# Working directory
root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/api/main"
  cmd = "go build -o ./tmp/api/main ./cmd/api/main.go"
  delay = 1000
  exclude_dir = ["tmp", "api", "k8s", "third_party", "test"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
  poll = false
  poll_interval = 500 # ms
  rerun = false
  rerun_delay = 500

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false